Hello everyone,
I'm sharing with you my little project commissioned by THP.
This project was about creating a two-player game, commonly known as "MORPION" or "TIC-TAC-TOE."
First, when you launch the program, you will need to choose the first player's username, and then you will be asked for the second player's.

Once the game starts, you will need to choose from several boxes, ranging from A1 to C3.
I'll let you see it for yourself.
Have fun playing!



